Repository JSD-0423/frontend-final-3, pull requests merged in 2023-07, with the labels that each got.

#1 Axios instance
  package-lock.json
  package.json
  public/favicon.ico
  public/logo.svg
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/Layouts/RootLayout.jsx
  src/Services/network.js
  src/Theme/Theme.js
  yarn.lock
Labels: Waiting-Review

#4 handpicked collections ready
  public/Assets/laura-chouette-Atomp7YdMaE-unsplash 1.png
  src/App.js
  src/Components/Banner/Banner.js
  src/Components/HandPicked/HandPicked.js
  src/Components/SingleTextCard/SingleTextCard.js
  src/Layouts/RootLayout.jsx
  src/Pages/Home/Home.js
  src/Theme/Theme.js
Labels: fix-conflict

#5 Added footer and it's fully responsive
  src/Components/FacebookIcon/FacebookIcon.js
  src/Components/Footer/Footer.js
  src/Components/Footer/StyledFooter.js
  src/Components/InstaIcon/InstaIcon.js
  src/Components/NavigationLink/NavigationLink.js
  src/Components/NavigationList/NavigationList.js
  src/Components/SocialMediaLinks/SocialMediaLinks.js
  src/Components/TextWithIcon/TextWithIcon.js
  src/Components/TwitterIcon/TwitterIcon.js
  src/Components/YoutubeIcon/YoutubeIcon.js
  src/Layouts/RootLayout.jsx
Labels: approved

#10 Landing page refactor
  src/Components/Cards/BrandCard/BrandCard.jsx
  src/Components/Cards/CardsCarousel/CardsCarousel.jsx
  src/Components/Cards/ProductCard/ProductCard.jsx
  src/Components/Header/Header.jsx
  src/Components/TitledContainerWithButton/TitledContainerWithButton.jsx
  src/Pages/Home/Home.js
  src/Pages/Home/components/NewArrivals.jsx
  src/Pages/Home/components/ShopByBrand.jsx
  yarn.lock
Labels: enhancement, Waiting-Review

#14 Landing page/refactor 2
  src/Components/Cards/BrandCard/BrandCard.jsx
  src/Components/Cards/CardsCarousel/CardsCarousel.jsx
  src/Components/Cards/ProductCard/ProductCard.jsx
  src/Components/Header/Header.jsx
  src/Components/InputWithIcon/InputWithIcon.jsx
  src/Components/NewArrivals/NewArrivals.jsx
  src/Components/ShopByBrand/ShopByBrand.jsx
  src/Components/TitledContainerWithButton/TitledContainerWithButton.jsx
  src/Layouts/RootLayout.jsx
  src/Pages/Home/Home.js
  src/Pages/Home/components/NewArrivals.jsx
  src/Pages/Home/components/ShopByBrand.jsx
Labels: enhancement, Waiting-Review

#16 Category page
  src/App.js
  src/Components/BreadCrumb/BreadCrumb.jsx
  src/Pages/Category/Category.jsx
Labels: Waiting-Review

#20 Signin Feature
  src/App.js
  src/Components/SigninForm/index.jsx
  src/Components/SigninForm/style.module.css
  src/Pages/PageNotFound/PageNotFound.jsx
  src/Pages/PageNotFound/index.jsx
  src/Pages/PageNotFound/style.css
  src/Pages/Signin/Signin.jsx
  src/Pages/Signin/index.jsx
  yarn.lock
Labels: requested-changes

#21 Api integration/new arrivals
  package-lock.json
  package.json
  src/App.js
  src/Components/Cards/ProductCard/ProductCard.jsx
  src/Components/NewArrivals/NewArrivals.jsx
  src/Components/TitledContainerWithButton/TitledContainerWithButton.jsx
  src/Pages/Category/Category.jsx
  src/Pages/Home/Home.js
  src/Services/network.js
  yarn.lock
Labels: requested-changes
